#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & 

picom --experimental-backends & 

$HOME/.config/polybar/launch.sh --shapes

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#xrandr --newmode "2560x1080_75.00"  294.00  2560 2744 3016 3472  1080 1083 1093 1130 -hsync +vsync 
#xrandr --addmode HDMI-2 "2560x1080_75.00" 
#xrandr --auto --output HDMI-2 --mode 2560x1080_75.00 --primary --left-of eDP-1

feh --bg-fill /home/fran/Descargas/groot2.jpg

wmname LG3D
